#!/usr/bin/env python2.7
# Solution to Project Euler Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def Fibonacci(end):
    prev = 1
    curr = 1
    sum = 0
    while (curr < end):
        if curr % 2 == 0:
            sum += curr
        c = curr
        curr = prev + c
        prev = c
    return sum

print Fibonacci(4000001)
